spring:
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/spotify"
            scope: "user-read-email"
            authorization-grant-type: authorization_code
        provider:
          spotify:
            authorization-uri: "https://accounts.spotify.com/authorize"
            token-uri: "https://accounts.spotify.com/api/token"
            user-info-uri: "https://api.spotify.com/v1/me"
            user-name-attribute: "id"